import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const token=new URLSearchParams(location.search).get('token');
const itemsEl=document.querySelector('#items'),summary=document.querySelector('#summary'),saved=document.querySelector('#saved');let state=[];let person='';let timer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function imgSrc(i){return i.image_data_url||i.image_path||''}
function render(){itemsEl.innerHTML=state.map(i=>`<article class="card" data-id="${i.id}"><img src="${esc(imgSrc(i))}" alt="${esc(i.name)}"><div><h2>${esc(i.name)}</h2>${i.description?`<p>${esc(i.description)}</p>`:''}<div class="choices"><label class="choice"><input type="radio" name="i${i.id}" value="true" ${i.interested===true?'checked':''}>Haluan tämän</label><label class="choice"><input type="radio" name="i${i.id}" value="false" ${i.interested===false?'checked':''}>En halua tätä</label></div><label>Kommentti<textarea maxlength="1000">${esc(i.comment||'')}</textarea></label></div></article>`).join('');
 document.querySelectorAll('.card').forEach(card=>{const id=Number(card.dataset.id),item=state.find(x=>x.id===id);card.querySelector('img').onclick=()=>{largeImage.src=imgSrc(item);imageDialog.showModal()};card.querySelectorAll('input').forEach(x=>x.onchange=()=>{item.interested=x.value==='true';scheduleSave();updateSummary()});card.querySelector('textarea').oninput=e=>{item.comment=e.target.value;scheduleSave()}});updateSummary()}
function updateSummary(){const answered=state.filter(x=>x.interested!==null).length;progressText.textContent=`Vastattu ${answered} / ${state.length}`;progressBar.style.width=`${state.length?answered/state.length*100:0}%`;yesList.innerHTML=state.filter(x=>x.interested===true).map(x=>`<li>${esc(x.name)}</li>`).join('')||'<li>Ei vielä valintoja</li>';noList.innerHTML=state.filter(x=>x.interested===false).map(x=>`<li>${esc(x.name)}</li>`).join('')||'<li>Ei vielä valintoja</li>';summary.hidden=false}
function scheduleSave(){saved.textContent='Tallennetaan…';clearTimeout(timer);timer=setTimeout(save,600)}
async function save(){const payload=state.map(i=>({furniture_id:i.id,interested:i.interested,comment:i.comment||''}));const {data,error}=await supabase.rpc('save_person_responses',{p_token:token,p_responses:payload});if(error||data!==true){saved.textContent='Tallennus epäonnistui';return}saved.textContent=`Tallennettu ${new Date().toLocaleTimeString('fi-FI',{hour:'2-digit',minute:'2-digit'})}`}
async function load(){if(!token){itemsEl.innerHTML='<div class="card">Linkistä puuttuu tunniste.</div>';return}const {data,error}=await supabase.rpc('get_person_form',{p_token:token});if(error||!data){itemsEl.innerHTML='<div class="card">Linkki ei ole voimassa.</div>';return}person=data.person_name;document.querySelector('#title').textContent=`Huonekalujen jako – ${person}`;state=data.items;render()}
load();
